// flow-typed signature: 9a2fc6f64f55996c11c9a0dd17f58b4c
// flow-typed version: <<STUB>>/@braintree/browser-detection_v1.7.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@braintree/browser-detection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@braintree/browser-detection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@braintree/browser-detection/browser-detection' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-android' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-chrome' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-edge' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ie' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ie10' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ie11' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ie9' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ios-firefox' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ios-safari' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ios-uiwebview' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ios-webview' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ios-wkwebview' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-ios' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-mobile-firefox' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/is-samsung' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/supports-payment-request-api' {
  declare module.exports: any;
}

declare module '@braintree/browser-detection/supports-popups' {
  declare module.exports: any;
}

// Filename aliases
declare module '@braintree/browser-detection/browser-detection.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/browser-detection'>;
}
declare module '@braintree/browser-detection/is-android.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-android'>;
}
declare module '@braintree/browser-detection/is-chrome.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-chrome'>;
}
declare module '@braintree/browser-detection/is-edge.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-edge'>;
}
declare module '@braintree/browser-detection/is-ie.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ie'>;
}
declare module '@braintree/browser-detection/is-ie10.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ie10'>;
}
declare module '@braintree/browser-detection/is-ie11.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ie11'>;
}
declare module '@braintree/browser-detection/is-ie9.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ie9'>;
}
declare module '@braintree/browser-detection/is-ios-firefox.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ios-firefox'>;
}
declare module '@braintree/browser-detection/is-ios-safari.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ios-safari'>;
}
declare module '@braintree/browser-detection/is-ios-uiwebview.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ios-uiwebview'>;
}
declare module '@braintree/browser-detection/is-ios-webview.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ios-webview'>;
}
declare module '@braintree/browser-detection/is-ios-wkwebview.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ios-wkwebview'>;
}
declare module '@braintree/browser-detection/is-ios.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-ios'>;
}
declare module '@braintree/browser-detection/is-mobile-firefox.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-mobile-firefox'>;
}
declare module '@braintree/browser-detection/is-samsung.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/is-samsung'>;
}
declare module '@braintree/browser-detection/supports-payment-request-api.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/supports-payment-request-api'>;
}
declare module '@braintree/browser-detection/supports-popups.js' {
  declare module.exports: $Exports<'@braintree/browser-detection/supports-popups'>;
}
