// flow-typed signature: ca278c95590fa96cf5d557f4864f758b
// flow-typed version: <<STUB>>/@braintree/iframer_v1.0.3/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@braintree/iframer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@braintree/iframer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@braintree/iframer/lib/assign' {
  declare module.exports: any;
}

declare module '@braintree/iframer/lib/default-attributes' {
  declare module.exports: any;
}

declare module '@braintree/iframer/lib/set-attributes' {
  declare module.exports: any;
}

// Filename aliases
declare module '@braintree/iframer/index' {
  declare module.exports: $Exports<'@braintree/iframer'>;
}
declare module '@braintree/iframer/index.js' {
  declare module.exports: $Exports<'@braintree/iframer'>;
}
declare module '@braintree/iframer/lib/assign.js' {
  declare module.exports: $Exports<'@braintree/iframer/lib/assign'>;
}
declare module '@braintree/iframer/lib/default-attributes.js' {
  declare module.exports: $Exports<'@braintree/iframer/lib/default-attributes'>;
}
declare module '@braintree/iframer/lib/set-attributes.js' {
  declare module.exports: $Exports<'@braintree/iframer/lib/set-attributes'>;
}
