// flow-typed signature: 0281c40b472816b40df849f2e77bb523
// flow-typed version: <<STUB>>/@braintree/sanitize-url_v2.1.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@braintree/sanitize-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@braintree/sanitize-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@braintree/sanitize-url/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@braintree/sanitize-url/index' {
  declare module.exports: $Exports<'@braintree/sanitize-url'>;
}
declare module '@braintree/sanitize-url/index.js' {
  declare module.exports: $Exports<'@braintree/sanitize-url'>;
}
declare module '@braintree/sanitize-url/test/test.js' {
  declare module.exports: $Exports<'@braintree/sanitize-url/test/test'>;
}
