// flow-typed signature: fcbf589eabfb6967c72385484f0415cb
// flow-typed version: <<STUB>>/@braintree/wrap-promise_v1.1.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@braintree/wrap-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@braintree/wrap-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@braintree/wrap-promise/lib/deferred' {
  declare module.exports: any;
}

declare module '@braintree/wrap-promise/lib/once' {
  declare module.exports: any;
}

declare module '@braintree/wrap-promise/lib/promise-or-callback' {
  declare module.exports: any;
}

declare module '@braintree/wrap-promise/wrap-promise' {
  declare module.exports: any;
}

// Filename aliases
declare module '@braintree/wrap-promise/lib/deferred.js' {
  declare module.exports: $Exports<'@braintree/wrap-promise/lib/deferred'>;
}
declare module '@braintree/wrap-promise/lib/once.js' {
  declare module.exports: $Exports<'@braintree/wrap-promise/lib/once'>;
}
declare module '@braintree/wrap-promise/lib/promise-or-callback.js' {
  declare module.exports: $Exports<'@braintree/wrap-promise/lib/promise-or-callback'>;
}
declare module '@braintree/wrap-promise/wrap-promise.js' {
  declare module.exports: $Exports<'@braintree/wrap-promise/wrap-promise'>;
}
