// flow-typed signature: 2b8dad20c74e011e9042c8e8d670047f
// flow-typed version: <<STUB>>/framebus_v3.0.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'framebus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'framebus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'framebus/lib/framebus' {
  declare module.exports: any;
}

// Filename aliases
declare module 'framebus/lib/framebus.js' {
  declare module.exports: $Exports<'framebus/lib/framebus'>;
}
