// flow-typed signature: 3f33b15e16c7a4898c82b204b053d675
// flow-typed version: <<STUB>>/inject-stylesheet_v1.0.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inject-stylesheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inject-stylesheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inject-stylesheet/config/karma' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/lib/filter-style-keys' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/lib/filter-style-values' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/lib/inject-stylesheet' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/lib/validate-selector' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/test/filter-style-keys' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/test/filter-style-values' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/test/inject-stylesheet' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/test/support/global' {
  declare module.exports: any;
}

declare module 'inject-stylesheet/test/validate-selector' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inject-stylesheet/config/karma.js' {
  declare module.exports: $Exports<'inject-stylesheet/config/karma'>;
}
declare module 'inject-stylesheet/index' {
  declare module.exports: $Exports<'inject-stylesheet'>;
}
declare module 'inject-stylesheet/index.js' {
  declare module.exports: $Exports<'inject-stylesheet'>;
}
declare module 'inject-stylesheet/lib/filter-style-keys.js' {
  declare module.exports: $Exports<'inject-stylesheet/lib/filter-style-keys'>;
}
declare module 'inject-stylesheet/lib/filter-style-values.js' {
  declare module.exports: $Exports<'inject-stylesheet/lib/filter-style-values'>;
}
declare module 'inject-stylesheet/lib/inject-stylesheet.js' {
  declare module.exports: $Exports<'inject-stylesheet/lib/inject-stylesheet'>;
}
declare module 'inject-stylesheet/lib/validate-selector.js' {
  declare module.exports: $Exports<'inject-stylesheet/lib/validate-selector'>;
}
declare module 'inject-stylesheet/test/filter-style-keys.js' {
  declare module.exports: $Exports<'inject-stylesheet/test/filter-style-keys'>;
}
declare module 'inject-stylesheet/test/filter-style-values.js' {
  declare module.exports: $Exports<'inject-stylesheet/test/filter-style-values'>;
}
declare module 'inject-stylesheet/test/inject-stylesheet.js' {
  declare module.exports: $Exports<'inject-stylesheet/test/inject-stylesheet'>;
}
declare module 'inject-stylesheet/test/support/global.js' {
  declare module.exports: $Exports<'inject-stylesheet/test/support/global'>;
}
declare module 'inject-stylesheet/test/validate-selector.js' {
  declare module.exports: $Exports<'inject-stylesheet/test/validate-selector'>;
}
