// flow-typed signature: 88d69bf0991f2b2e7a83dc45afddbabd
// flow-typed version: <<STUB>>/restricted-input_v1.2.7/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'restricted-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'restricted-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'restricted-input/dist/restricted-input' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/constants' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/device' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/formatter' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/formatter/parse-pattern' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/input-selection' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/is-backspace' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/is-delete' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/is-valid-element' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/key-cannot-mutate-value' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/restricted-input' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/strategies/android-chrome' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/strategies/base' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/strategies/ie9' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/strategies/ios' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/strategies/kitkat-chromium-based-webview' {
  declare module.exports: any;
}

declare module 'restricted-input/lib/strategies/noop' {
  declare module.exports: any;
}

declare module 'restricted-input/main' {
  declare module.exports: any;
}

declare module 'restricted-input/supports-input-formatting' {
  declare module.exports: any;
}

// Filename aliases
declare module 'restricted-input/dist/restricted-input.js' {
  declare module.exports: $Exports<'restricted-input/dist/restricted-input'>;
}
declare module 'restricted-input/lib/constants.js' {
  declare module.exports: $Exports<'restricted-input/lib/constants'>;
}
declare module 'restricted-input/lib/device.js' {
  declare module.exports: $Exports<'restricted-input/lib/device'>;
}
declare module 'restricted-input/lib/formatter/index' {
  declare module.exports: $Exports<'restricted-input/lib/formatter'>;
}
declare module 'restricted-input/lib/formatter/index.js' {
  declare module.exports: $Exports<'restricted-input/lib/formatter'>;
}
declare module 'restricted-input/lib/formatter/parse-pattern.js' {
  declare module.exports: $Exports<'restricted-input/lib/formatter/parse-pattern'>;
}
declare module 'restricted-input/lib/input-selection.js' {
  declare module.exports: $Exports<'restricted-input/lib/input-selection'>;
}
declare module 'restricted-input/lib/is-backspace.js' {
  declare module.exports: $Exports<'restricted-input/lib/is-backspace'>;
}
declare module 'restricted-input/lib/is-delete.js' {
  declare module.exports: $Exports<'restricted-input/lib/is-delete'>;
}
declare module 'restricted-input/lib/is-valid-element.js' {
  declare module.exports: $Exports<'restricted-input/lib/is-valid-element'>;
}
declare module 'restricted-input/lib/key-cannot-mutate-value.js' {
  declare module.exports: $Exports<'restricted-input/lib/key-cannot-mutate-value'>;
}
declare module 'restricted-input/lib/restricted-input.js' {
  declare module.exports: $Exports<'restricted-input/lib/restricted-input'>;
}
declare module 'restricted-input/lib/strategies/android-chrome.js' {
  declare module.exports: $Exports<'restricted-input/lib/strategies/android-chrome'>;
}
declare module 'restricted-input/lib/strategies/base.js' {
  declare module.exports: $Exports<'restricted-input/lib/strategies/base'>;
}
declare module 'restricted-input/lib/strategies/ie9.js' {
  declare module.exports: $Exports<'restricted-input/lib/strategies/ie9'>;
}
declare module 'restricted-input/lib/strategies/ios.js' {
  declare module.exports: $Exports<'restricted-input/lib/strategies/ios'>;
}
declare module 'restricted-input/lib/strategies/kitkat-chromium-based-webview.js' {
  declare module.exports: $Exports<'restricted-input/lib/strategies/kitkat-chromium-based-webview'>;
}
declare module 'restricted-input/lib/strategies/noop.js' {
  declare module.exports: $Exports<'restricted-input/lib/strategies/noop'>;
}
declare module 'restricted-input/main.js' {
  declare module.exports: $Exports<'restricted-input/main'>;
}
declare module 'restricted-input/supports-input-formatting.js' {
  declare module.exports: $Exports<'restricted-input/supports-input-formatting'>;
}
